### ISSUE TITLE
Pulling IG locally?

### ISSUE THREAD

**Issue by 484-studio** [marieqg/medium-instagram#1]
This is a little outside of what the plugin is intended for, I do realise.
However, I'm wondering if you could point me in the right direction of scraping my IG data and storing it locally?
I'd like to archive my old IG posts from my profile on my Gatsby website, then delete them off my profile.

I'm assuming every rebuild will re-scrape my Instagram, leaving me with an empty archive page in the future.

**Comment by marieqg** [comment]
Hello, 
You are assuming correctly. That's why that I think once you get the data, you need to make a copy of it on your own server. 
In that way, your data will be stored. But it also assume that the data you'll pull from gatsby to display on your archive page as to come from your own server. 
Hope it helped :)

**Comment by marieqg** [comment]
It's not really an issue with the project, so I'm closing it btw :)
